# seed_data.py — All developer profiles and project data
# Split into DEVELOPERS_DATA (company info) and PROJECTS_DATA (per-project details)

# Unsplash real estate placeholder images
IMG = {
    "apt1": "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&q=80&w=800",
    "apt2": "https://images.unsplash.com/photo-1567684014761-b65e2e59b9eb?auto=format&fit=crop&q=80&w=800",
    "apt3": "https://images.unsplash.com/photo-1574362848149-11496d93a7c7?auto=format&fit=crop&q=80&w=800",
    "apt4": "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&q=80&w=800",
    "apt5": "https://images.unsplash.com/photo-1515263487990-61b07816b324?auto=format&fit=crop&q=80&w=800",
    "villa1": "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&q=80&w=800",
    "villa2": "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&q=80&w=800",
    "villa3": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=800",
    "sky1": "https://images.unsplash.com/photo-1462826303086-329426d1aef5?auto=format&fit=crop&q=80&w=800",
    "sky2": "https://images.unsplash.com/photo-1448630360428-65456659e864?auto=format&fit=crop&q=80&w=800",
    "sky3": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=800",
    "int1": "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&q=80&w=800",
    "int2": "https://images.unsplash.com/photo-1600566753086-00f18f6b8e5d?auto=format&fit=crop&q=80&w=800",
    "pool1": "https://images.unsplash.com/photo-1572120360610-d971b9d7767c?auto=format&fit=crop&q=80&w=800",
    "club1": "https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?auto=format&fit=crop&q=80&w=800",
    "green1": "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&q=80&w=800",
    "com1": "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=800",
    "lux1": "https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?auto=format&fit=crop&q=80&w=800",
    "lux2": "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&q=80&w=800",
    "town1": "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&q=80&w=800",
}

def _imgs(keys):
    """Helper: generate image list from key list"""
    result = []
    for i, k in enumerate(keys):
        result.append({
            "image_url": IMG.get(k, IMG["apt1"]),
            "caption": None,
            "is_primary": i == 0,
            "sort_order": i,
        })
    return result

DEVELOPERS_DATA = [
    {
        "name": "Prestige Group",
        "slug": "prestige-group",
        "about": "Prestige Group is a leading Indian real estate development company founded in 1986 and headquartered in Bengaluru. It develops residential apartments, villas, commercial offices, shopping malls, and hospitality projects across major cities like Bengaluru, Chennai, Hyderabad, and Mumbai. Known for landmark developments such as UB City and Forum Mall, the company has completed hundreds of projects covering millions of square feet.",
        "founded_year": 1986,
        "headquarters": "Bengaluru",
        "total_projects": 2,
    },
    {
        "name": "Godrej Properties",
        "slug": "godrej-properties",
        "about": "Godrej Properties is a prominent Indian real estate company established in 1990 and headquartered in Mumbai. It is part of the well-known Godrej Group and focuses on developing residential, commercial, and township projects across major cities. The company is known for combining innovation, sustainability, and quality construction.",
        "founded_year": 1990,
        "headquarters": "Mumbai",
        "total_projects": 2,
    },
    {
        "name": "Brigade Group",
        "slug": "brigade-group",
        "about": "Brigade Group is a leading Indian real estate developer founded in 1986 and headquartered in Bengaluru. The company develops residential, commercial, retail, and hospitality projects across major cities such as Bengaluru, Chennai, Hyderabad, and Kochi. Known for projects like Brigade Gateway and Orion Mall.",
        "founded_year": 1986,
        "headquarters": "Bengaluru",
        "total_projects": 4,
    },
    {
        "name": "Ramky",
        "slug": "ramky",
        "about": "Ramky Group is an Indian infrastructure and environmental services company founded in 1994 and headquartered in Hyderabad. It operates across sectors such as infrastructure development, construction, waste management, and real estate.",
        "founded_year": 1994,
        "headquarters": "Hyderabad",
        "total_projects": 4,
    },
    {
        "name": "Rajapushpa Properties",
        "slug": "rajapushpa-properties",
        "about": "Rajapushpa Properties is a real estate development company based in Hyderabad, India. It focuses mainly on residential apartment projects, gated communities, and premium housing developments. Known for building modern, large-scale residential layouts with amenities.",
        "founded_year": None,
        "headquarters": "Hyderabad",
        "total_projects": 8,
    },
    {
        "name": "ASBL",
        "slug": "asbl",
        "about": "ASBL (Ashoka Builders) is a real estate development company based in Hyderabad, India. It focuses mainly on residential projects such as premium apartments and gated communities designed for urban living. Known for modern architecture and efficient space planning.",
        "founded_year": None,
        "headquarters": "Hyderabad",
        "total_projects": 5,
    },
    {
        "name": "Lansum Properties",
        "slug": "lansum-properties",
        "about": "Lansum Properties is a real estate development company based in Hyderabad, India. It primarily focuses on premium residential projects such as luxury apartments and gated communities. Known for delivering modern designs and quality construction.",
        "founded_year": None,
        "headquarters": "Hyderabad",
        "total_projects": 3,
    },
    {
        "name": "Candeur Developers",
        "slug": "candeur-developers",
        "about": "Candeur Developers is a Hyderabad-based real estate company known for building large-scale residential communities. The company focuses on modern design, quality construction, and customer-centric projects with amenities like clubhouses, green spaces, and smart living features.",
        "founded_year": None,
        "headquarters": "Hyderabad",
        "total_projects": 5,
    },
    {
        "name": "Casagrand",
        "slug": "casagrand",
        "about": "Casagrand is a leading Indian real estate company founded in 2003 and headquartered in Chennai. It specializes in developing residential projects such as apartments, villas, and gated communities across major South Indian cities. It has completed over 100 projects.",
        "founded_year": 2003,
        "headquarters": "Chennai",
        "total_projects": 8,
    },
    {
        "name": "Cybercity Builders",
        "slug": "cybercity-builders",
        "about": "Cybercity Builders & Developers is a well-known real estate company based in Hyderabad, established around 2005. It focuses on developing high-rise apartments, gated communities, and integrated township projects across Hyderabad, Chennai, and Visakhapatnam.",
        "founded_year": 2005,
        "headquarters": "Hyderabad",
        "total_projects": 5,
    },
    {
        "name": "Hallmark Builders",
        "slug": "hallmark-builders",
        "about": "For more than 15 years, Hallmark has been the pinnacle of excellence and innovation. Founded in 2008, Hallmark is now a recognized builder of impeccable and well-designed projects whose bracket ranges from super luxury, ultra-premium, to premium for different segments.",
        "founded_year": 2008,
        "headquarters": "Hyderabad",
        "total_projects": 9,
    },
    {
        "name": "Sattva Group",
        "slug": "sattva-group",
        "about": "Sattva Group is a dynamic real estate conglomerate headquartered in Bengaluru with presence in 8 Indian cities. The group has delivered over 124 projects and has 80 million sq ft of completed space. It is a CRISIL AA/Stable rated developer.",
        "founded_year": None,
        "headquarters": "Bengaluru",
        "total_projects": 1,
    },
    {
        "name": "Jain Constructions",
        "slug": "jain-constructions",
        "about": "Jain Constructions was founded to create integrated townships and lifestyle patterns. With promoters having two decades of experience, it has 6 on-going projects and more than 38 projects completed across Hyderabad in residential, commercial and villa verticals.",
        "founded_year": None,
        "headquarters": "Hyderabad",
        "total_projects": 5,
    },
    {
        "name": "EAPL",
        "slug": "eapl",
        "about": "EAPL Group (Engineer Associates Pvt. Ltd.) has been a trusted name in real estate since 1998, with a strong presence in Hyderabad and Bangalore. Led by Managing Director A. Praveen, the company is known for engineering excellence and innovative developments.",
        "founded_year": 1998,
        "headquarters": "Hyderabad",
        "total_projects": 2,
    },
    {
        "name": "Trilight Developers",
        "slug": "trilight-developers",
        "about": "Trilight Developers is a Hyderabad-based real estate developer focused on delivering modern residential apartment projects, mainly in emerging growth corridors of the city. Known for mid-range to premium apartment projects with quality construction and contemporary design.",
        "founded_year": None,
        "headquarters": "Hyderabad",
        "total_projects": 2,
    },
    {
        "name": "Om Sree",
        "slug": "om-sree",
        "about": "Inspired by the concept of enabling a new Indian lifestyle, Om Sree brought a shift in quality housing spaces. With a presence of over 23 years, Om Sree has become an end-to-end solution provider for housing requirements.",
        "founded_year": None,
        "headquarters": "Hyderabad",
        "total_projects": 3,
    },
    {
        "name": "Raghava Projects",
        "slug": "raghava-projects",
        "about": "At Raghava, they transcend convention to redefine the very essence of living. With world-class residences, peerless amenities, and experiences that exceed expectations, Raghava crafts legacies. Rooted in a singular core belief where vision meets land, and ambition meets possibility.",
        "founded_year": None,
        "headquarters": "Hyderabad",
        "total_projects": 4,
    },
    {
        "name": "Anvita",
        "slug": "anvita",
        "about": "With a proven track record since 2005, Anvita has grown to become a well-respected and trusted name. Their team of dedicated professionals ensures every project is completed with precision and accuracy using latest technology and best practices.",
        "founded_year": 2005,
        "headquarters": "Hyderabad",
        "total_projects": 2,
    },
    {
        "name": "MSN Realty",
        "slug": "msn-realty",
        "about": "Established in 2021, MSN Realty harnesses the legacy of MSN's success in the pharmaceutical industry. MSN Realty is poised to develop 20 million sq ft of residential and commercial spaces over the next five years in Hyderabad's most desirable locations.",
        "founded_year": 2021,
        "headquarters": "Hyderabad",
        "total_projects": 1,
    },
    {
        "name": "Sukhi",
        "slug": "sukhi",
        "about": "Sukhi group believes that the responsibility to care for Mother Earth is an individual job. Every community has a minimum of 60% open space with sustainable design including rainwater harvesting and dedicated sewage treatment plants.",
        "founded_year": None,
        "headquarters": "Hyderabad",
        "total_projects": 2,
    },
    {
        "name": "Anandha Homes",
        "slug": "anandha-homes",
        "about": "Anandha Homes is a real estate and construction company based in South India. It focuses on building residential projects such as apartments and individual homes, offering budget-friendly and mid-range housing options with modern amenities.",
        "founded_year": None,
        "headquarters": "Chennai",
        "total_projects": 3,
    },
    {
        "name": "Vertex",
        "slug": "vertex",
        "about": "Vertex is a well-known real estate developer based in Hyderabad, established in 1994. It mainly operates in Telangana and Andhra Pradesh, developing residential and commercial projects such as apartments, villas, gated communities, and plotted developments.",
        "founded_year": 1994,
        "headquarters": "Hyderabad",
        "total_projects": 4,
    },
    {
        "name": "Anuhar Homes",
        "slug": "anuhar-homes",
        "about": "Anuhar Homes is a real estate developer based in Hyderabad, established in 2007. It focuses on building residential projects like apartments and gated communities across areas such as Manikonda, Kollur, Miyapur, and Pocharam.",
        "founded_year": 2007,
        "headquarters": "Hyderabad",
        "total_projects": 3,
    },
]
